version: '3.3'

services:
  web:
    image: registry.optdeal.com/sda/web:latest
    build:
      args:
        BUILD_ENV: prod
    restart: unless-stopped
    volumes:
      - /var/www
      - '.:/source'

  mysql:
    restart: unless-stopped
