version: '3.3'

services:
  web:
    build: .
    ports:
      - '${PORT}:${PORT}'
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    depends_on:
      - mysql
    tty: true
    networks:
      - backend

### MySQL Container #########################################

  mysql:
    image: leafney/docker-alpine-mysql
    environment:
      - MYSQL_USER_DB=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_USER_PWD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PWD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - /var/lib/mysql
      - /var/log/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - backend


### Networks Setup ############################################

networks:
  backend:
    driver: "bridge"
