version: '3.3'

services:
  web:
    image: registry.optdeal.com/sda/web:latest
    build:
      args:
        BUILD_ENV: prod
    restart: unless-stopped
    deploy:
      placement:
        constraints: [node.role == manager]

  mysql:
    restart: unless-stopped
    deploy:
      placement:
        constraints: [node.role == manager]
