version: '3.3'

services:
  web:
    build:
      context: .
      args:
        BUILD_ENV: dev
    volumes:
      - '.:/var/www'
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"

### Volumes Setup #############################################
volumes:
  mysql:
    driver: "local"
