<?php // autogenerated on DATE by SurvosCrudBundle:Generated:Custom/Controller/{phpName}Controller.php.twig


namespace AppBundle\Controller;

use AppBundle\Entity\DecisionType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response as HttpResponse;
use Symfony\Component\HttpFoundation\Request;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;

use Pagerfanta\Pagerfanta;
use Pagerfanta\Adapter\PropelAdapter;

use AppBundle\Form\Type\DecisionTypeType;
use Posse\SurveyBundle\Controller\PosseController;

/**
 * @Route("/fda/DecisionType")
*/
class DecisionTypeController extends Controller // BaseDecisionTypeController
{

    /**
     * @Route("/edit/{id}", requirements={"id"="\d+", }, name="crud_fda_DecisionType_edit")
     * @Template("AppBundle:DecisionType:edit.html.twig")
     */
    function editAction(Request $request, DecisionType $decisionType) {
        $form = $this->createForm(new DecisionTypeType(), $decisionType);
        $form->handleRequest($request);
            if ($form->isValid()) {
                $decisionType->save();

                $key['id'] = $decisionType->getId();
                return $this->redirect($this->generateUrl('crud_fda_DecisionType_display',
                  $key));
                  // array('id' => $decisionType->getPrimaryKey())));
            }

        return array(
            'decisionType' => $decisionType,
            'form' => $form->createView()
        );
    }
        /**
    * @Route("/show/{id}", name="fda_decisionType_show")
    * @Template()
    */
    function showAction(Request $request, DecisionType $decisionType)
    {
        return ['d'=>$decisionType];
    }


    }

