<?php // autogenerated on DATE by SurvosCrudBundle:Generated:Custom/Controller/{phpName}Controller.php.twig


namespace AppBundle\Controller;

use AppBundle\Entity\Statute;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response as HttpResponse;
use Symfony\Component\HttpFoundation\Request;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;

use Pagerfanta\Pagerfanta;
use Pagerfanta\Adapter\PropelAdapter;

use AppBundle\Form\Type\StatuteType;
use AppBundle\Controller\BaseStatuteController;
use Posse\SurveyBundle\Controller\PosseController;

/**
 * @Route("/fda/origStatute")
*/
class OrigStatuteController extends Controller
{

    /**
     * @Route("/edit/{id}", requirements={"id"="\d+", }, name="crud_fda_Statute_edit")
     * @Template("AppBundle:Statute:edit.html.twig")
     */
    function editAction(Request $request, Statute $statute) {
        $form = $this->createForm(new StatuteType(), $statute);
        $form->handleRequest($request);
            if ($form->isValid()) {
                $statute->save();

                $key['id'] = $statute->getId();
                return $this->redirect($this->generateUrl('fda_statute_show',
                  $key));
                  // array('id' => $statute->getPrimaryKey())));
            }

        return array(
            'statute' => $statute,
            'form' => $form->createView()
        );
    }
        /**
    * @Route("/show/{id}", name="orig_fda_statute_show")
    * @Template()
    */
    function showAction(Request $request, Statute $statute)
    {
        return ['d'=>$statute];
    }


    }

