<?php

namespace AppBundle\Repository;

/**
 * RawInspectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RawInspectionRepository extends \Doctrine\ORM\EntityRepository
{
}
